### ISSUE TITLE
python3 main.py stuck in infinite loop of login to chatgpt

### ISSUE THREAD

**Issue by UriZafrir** [kamillobinski/chatgpt-terminal#4]
Hi,
After installing the tool and activating with "python3 main.py", after I press login, the browser closes and the terminal respawns it resulting in an infinite loop.
I am using mac m1.
Please help..
![image](https://user-images.githubusercontent.com/35652384/216190820-268339e8-de1e-46eb-a9b2-4f0d60a2884e.png)
https://user-images.githubusercontent.com/35652384/216191181-0054aa2e-8214-4e20-8e3a-8de58fbec018.mov

**Comment by kyleslight** [comment]
I got the same issue on my M2 chip Macbook

**Comment by kalasbralla** [comment]
Same issue here. The browser gets spawned. I barely manage to click to login link then I get an infinite loop.

...
Failed to refresh session!
Failed to refresh session!
...

Edit: Linux.

**Comment by kamillobinski** [comment]
Thanks for submitting your pull request. I appreciate your interest in my project, but I want to let you know that this project was created solely for fun and won't be maintained or updated. Therefore, I am archiving the project.

If anyone is interested in improving, fixing, or modifying the project to suit their needs, they are more than welcome to do so on their own. However, please keep in mind that I won't be available to provide any support or assistance.
